server:
  port: 8080

# Database connection settings
spring:
  application:
    name: moodmate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Put the name of the database created on your local MySQL server
    url: jdbc:mysql://localhost:3306/db_moodmate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # Put the user credentials created in your MySQL server
    username: user_moodmate
    password: 1204
  thymeleaf:
    cache: false

# Spring Data JPA settings
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # Use 'create' when first running the project, then switch to 'update'
